FROM node:latest
WORKDIR /app
COPY ./package.json .
COPY ./angular.json .
RUN npm i -g @angular/cli@9.0.5
RUN npm i -g @angular-devkit/build-angular@0.900.5
RUN npm i -n
COPY . .
CMD ["npm", "run", "start"]
